# Generated by Django 2.0.1 on 2018-01-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_perfil_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
