# Generated by Django 2.0.1 on 2018-01-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20180109_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='caratula',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
